# Generated by Django 3.0.6 on 2020-05-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('released', models.DateTimeField(verbose_name='date released')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
