# Generated by Django 3.0.6 on 2020-05-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=15)),
                ('userpw', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
